### ISSUE TITLE
Set gpu_mem to 16 for server

### ISSUE THREAD

**Issue by jkrauss82** [debian-pi/raspbian-ua-netinst#109]
Hello,

first: great job, I just ran through an unattended installation and it worked like a charm!

A remark/suggestion: as most ua-netinst users will probably not use a GUI (at least if they choose 'server') why don't you set the default gpu_mem config to 16 to have more free RAM?

Best,

Jonas

**Comment by diederikdehaas** [comment]
This is now fixed with the merge of #335
