### ISSUE TITLE
[NAB] Hang when copying boot files to µSD due to un-partitioned space.

### ISSUE THREAD

**Issue by mpmc** [debian-pi/raspbian-ua-netinst#165]
Hey folks,

Setting up my B+ with a newly opened µSD and noticed that it was failing to copy over boot files due to the µSD being partitioned [OOTB] with 4M of un-partitioned space at the start with the rest being fat. 

Instead of failing gracefully it just completely hangs, no reboot, no error, nothing.

Removing the the un-partitioned space solves the issue, the installer continues quite happily.
I wouldn't say that is a bug at all [Hence the Not A Bug in the title] but I thought you guys might want to be aware so you can check for stupid things like this [Thanks Kingston!].

**Comment by Mausy5043** [comment]
Closing this issue for now, assuming it is resolved. If you feel the closure is in error, please feel free to re-open and add new information.
