### ISSUE TITLE
older kernel version (3.2.0-4-rpi)

### ISSUE THREAD

**Issue by bbinet** [debian-pi/raspbian-ua-netinst#166]
I was wondering if it was possible to build an image with an older raspbian kernel version (3.2.0-4-rpi).

The kernel version currently seems to be hardcoded in `build.sh`, `update.sh` and `scripts/etc/init.d/rcS`:

```
KERNEL_VERSION=3.12-1-rpi
```

Would it be possible to make the `KERNEL_VERSION` configurable?

**Comment by Mausy5043** [comment]
The bug referred to seems to have been resolved.  
@bbinet : Is this still a issue?

**Comment by diederikdehaas** [comment]
> The bug referred to seems to have been resolved.

That's not the impression I got. But I mostly considered this issue to be as a way for ppl to specify their own kernel package. Not sure that's wise, but it was the thought.

**Comment by Mausy5043** [comment]
@bbinet : Is this still an issue with the newer kernel?

**Comment by bbinet** [comment]
Sorry, I don't know, I'm now working with resinos for new boards.
