### ISSUE TITLE
OrangePI Support?

### ISSUE THREAD

**Issue by andriej** [debian-pi/raspbian-ua-netinst#177]
In short words: Is there any chance of getting the netinst to support OrangePI in top(which is RPi compatible)?

I can't even describe how awesome it would be.

**Comment by goranche** [comment]
have you actually tried it already?
as far as I can tell (from documents, don't have an Orange Pi to test for myself), it should be able to run the same images, so the installer might work as is...

**Comment by diederikdehaas** [comment]
What's the difference between an OrangePi and a BananaPi?
Like @goranche said, it should work ... but why not use the Debian armhf port?
I have no objections to supporting BananaPi/OrangePi, but since I don't have one, I can't test it ...

**Comment by diederikdehaas** [comment]
What's the status on this issue?

**Comment by diederikdehaas** [comment]
Closing this issue since the reporter seems to have lost interest. 
If someone does want this and is willing to provide feedback, feel free to reopen it.
