### ISSUE TITLE
ln: failed to create hard link

### ISSUE THREAD

**Issue by jerjac** [debian-pi/raspbian-ua-netinst#18]
Hi! Great job, great tool I love the minimalist approach :)

i have a problem and think it might be related to this particular install, each time I use apt to intsall a package I get these lines showing up:

Processing triggers for initramfs-tools ...
ln: failed to create hard link `/boot/initrd.img-3.10-3-rpi.dpkg-bak' =>`/boot/initrd.img-3.10-3-rpi': Operation not permitted
update-initramfs: Generating /boot/initrd.img-3.10-3-rpi

I did follow what was written in the readme after instal (updating the kernel/firmware)

Any idea on what it means, causes this and how to fix it ? Thanks

**Comment by Zorono** [comment]
i am not sure if this is the right place to report this but linux 6.5.0 is throwing this error... (please note that i am using Kali Linux)

```
Setting up initramfs-tools (0.142) ...
update-initramfs: deferring update (trigger activated)     Processing triggers for initramfs-tools (0.142) ...
ln: failed to create hard link '/boot/initrd.img-6.5.0-kali3-arm64.dpkg-bak' => '/boot/initrd.img-6.5.0-kali3-arm64': Operation not permitted
update-initramfs: Generating /boot/initrd.img-6.5.0-kali3-arm64

cryptsetup: ERROR: Couldn't resolve device /dev/root       cryptsetup: WARNING: Couldn't determine root device
W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
W: mdadm: failed to auto-generate temporary mdadm.conf file.
zstd: error 70 : Write error : cannot write block : No space left on device
E: mkinitramfs failure zstd -q -9 -T0 70
update-initramfs: failed for /boot/initrd.img-6.5.0-kali3-arm64 with 1.
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
```

**Comment by JedMeister** [comment]
> ```zstd: error 70 : Write error : cannot write block : No space left on device```

Specifically: `No space left on device`

I reckon that's your issue! :grin:
