### ISSUE TITLE
No space left on device (1.0.7-beta)

### ISSUE THREAD

**Issue by Mausy5043** [debian-pi/raspbian-ua-netinst#190]
As promised.
Tried to build a Raspberry Pi with the 1.0.7-beta:
```
gzip: 
stdout: No space left on device
update-initramfs: failed for /boot/initrd.img-3.18.0-trunk-rpi with 1.
dpkg: error processing initramfs-tools (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E
: 
Sub-process /usr/bin/dpkg returned an error code (1)

E: Internal error: install

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...
```
(I could've sworn there was already an issue logged for this, but I can't find it anymore.)

Rebooting as I type with `bootsize=+64M` in `...\init.d\rcS`

**Comment by diederikdehaas** [comment]
A bit more info is needed here.
What were you trying to do? When did it fail? Do you have a log file you could share? What configuration files did you use?

**Comment by tais** [comment]
I have had the same issue, raspi B2, following config

preset=server
mirror=http://mirrordirector.raspbian.org/raspbian/
release=jessie
hostname=xxxxx
domainname=xxxx.local
rootpw=xxxxxxxxx
cdebootstrap_cmdline=
timeserver=nl.pool.ntp.org
ip_addr=xxx.xxx.xxx.xxx
ip_netmask=xxx.xxx.xxx.xxx
ip_gateway=xxx.xxx.xxx.xxx
ip_nameservers=xxx.xxx.xxx.xxx

**Comment by Mausy5043** [comment]
Relevant part of the logfile is up there. I'm afraid I destroyed the rest. If you really need it I could re-create  another one later. But I don't see the point right now.
Some background: R-PI B-type, 4GB SD card. I built the SD-card image as usual. Then inserted it into the Pi.

installer-config.txt:
```
packages="apt-utils,avahi-daemon,bc,git,htop,libnss-mdns,logrotate,lsof,nano,nfs-common"
packages="$packages,python,raspi-copies-and-fills,rsync,screen,sudo"
hostname=raspberrypi
cmdline="dwc_otg.lpm_enable=0 console=tty1 noatime loglevel=2 cgroup_enable=memory elevator=noop"
rootfstype=f2fs
label=$hostname
```
I'm watching a new boot right now with the `bootsize=+64M`. That seems to have done the trick.

**Comment by diederikdehaas** [comment]
So it fails during the installation?

**Comment by tais** [comment]
yup, runs out of space as it seems

**Comment by Mausy5043** [comment]
Yes.
Mine just past the `post-install` flawlessly.
I'm calling this one solved.
Shall I pull the solution?

**Comment by tais** [comment]
yup, it's rebooting now, bootsize 50M seems to be too small for the B2 install, needs atleast 64M I suppose if it works with Mausy5043, I had it at 70M and it works well

**Comment by diederikdehaas** [comment]
@Mausy5043 that's fine (propose it to the v1.0.x branch)

I/we aren't sure yet what the best/full solution is though. I already figured it probably needed to be expanded to 64M by default, but @goranche suggested that doubling it would probably be better (since you'd have very little space left). Another solution would be to delete the RPi1 installer.cpio and installer kernel on a RPi 2 (and vice versa) to reclaim some space.

**Comment by diederikdehaas** [comment]
@Mausy5043 could you modify your PR? And while you're at it, also update the README.md to show the new default?

**Comment by Mausy5043** [comment]
@diederikdehaas I agree. 64M is a bit tight. Works for now.
What would you like changed?

**Comment by diederikdehaas** [comment]
> What would you like changed?

you proposed it to be merged with master and I'd like that to be the v1.0.x branch

**Comment by Mausy5043** [comment]
Oh right. Sorry about that.

**Comment by diederikdehaas** [comment]
np

**Comment by diederikdehaas** [comment]
@Mausy5043 your install was on a Pi 1, right?

**Comment by Mausy5043** [comment]
Yes Pi 1 (B).

**Comment by diederikdehaas** [comment]
Ok, wanted to make sure the right kernel was getting installed.

This issue should be resolved by the merge of @Mausy5043's PR.
I'll leave it open for now so we don't get others issues about this same problem.

**Comment by Mausy5043** [comment]
Up and running:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  3.7G  1.1G  2.6G  30% /
[...]
/dev/mmcblk0p1   61M   41M   21M  66% /boot
```

On 1.0.6:
```
/dev/mmcblk0p1   48M   37M   12M  77% /boot
```
Seems we need about >=30% free space on the boot partition to allow for unzipping of packages during installation.

**Comment by pgrandin** [comment]
I just faced this issue today. Can you guys please release a new image? This might impact quite a few people. Thanks!

**Comment by goranche** [comment]
oh, that's fun... :unamused:

**Comment by diederikdehaas** [comment]
This issue should now be fixed with the release of [v1.0.7-RC](https://github.com/debian-pi/raspbian-ua-netinst/releases/tag/v1.0.7-RC)

**Comment by Mausy5043** [comment]
I'll test this weekend. It's someones birthday next monday and he gave me the day off to celebrate it. :wink:
How better to celebrate it than by testing a new release. :smile:

**Comment by diederikdehaas** [comment]
haha :+1:

**Comment by Mausy5043** [comment]
It's working on v1.0.7-RC

**Comment by aykevl93** [comment]
I hit this issue while upgrading the `initramfs-tools` package.
I worked around it by moving `/boot/initrd.img-3.12-1-rpi` to `/home/initrd.img-3.12-1-rpi`, installing the update, and moving it back. I haven't tried rebooting yet.

**Comment by Mausy5043** [comment]
I think that any installations created with the (old) 3.12 kernels will have this problem when trying to upgrade. As the newer kernels/initrd.img require more space on the /boot partition than is currently provided.
If you want to upgrade you'll need to rebuild with the 1.0.7-RC release or find a way to grow the /boot partition to 128MB.
