### ISSUE TITLE
Allow overriding the RPi version to install for

### ISSUE THREAD

**Issue by hadess** [debian-pi/raspbian-ua-netinst#194]
After installing the system through QEmu:

```
$ cat /boot/config.txt 
[piUNKNOWN !!]
kernel=vmlinuz-
initramfs initrd.img- followkernel
```

It should be possible to override the detected Pi version through a command-line argument, so that the config.txt and image created is usable on a real Raspberry Pi.

```
raspbian-ua-netinst.hw=1
```

for example. Let me know if that's acceptable, I'll create a patch.

**Comment by goranche** [comment]
this might be a good idea :thought_balloon: 
although probably not through a command-line argument, but an entry in the config file...

**Comment by diederikdehaas** [comment]
How about defaulting to Pi 1?

**Comment by diederikdehaas** [comment]
With the merging of #309 I think this issue is resolved.
