### ISSUE TITLE
Allow overriding Debian sources

### ISSUE THREAD

**Issue by hadess** [debian-pi/raspbian-ua-netinst#195]
Not sure whether that's something you want.

**Comment by goranche** [comment]
there was some talk about this already (can't find the corresponding issue at this time :blush: ), and might be done in the future

**Comment by goranche** [comment]
@diederikdehaas any additional comments? otherwise, close this one

**Comment by diederikdehaas** [comment]
I think we already have this, but in the v1.1.x branch:
https://github.com/debian-pi/raspbian-ua-netinst/tree/v1.1.x/config/apt

**Comment by goranche** [comment]
darn... I knew it sounded familiar, but couldn't find an issue mentioning it... :grin: 
didn't think of going through the PRs :blush:

**Comment by diederikdehaas** [comment]
Since the support for this is already present, I'm closing this issue.
