### ISSUE TITLE
Can't login at first boot up

### ISSUE THREAD

**Issue by KoopsF** [debian-pi/raspbian-ua-netinst#208]
Hello,
I have a raspberry pi b+ and i want to use a 2GB sd card (1.8GB)
I've used raspbian-ua-netinst-v1.0.6 and I think that the installation was successful.
After the installation it booted up and prompted for a login and password.
I tried login: pi and password: raspberry. and login: pi password: raspbian.
But it returns a incorrect login.
what am I doing wrong?

**Comment by diederikdehaas** [comment]
the installation doesn't create an additional user, so there's only the 'root' user, with password 'raspbian' (unless changed through config file).

**Comment by KoopsF** [comment]
pi login: root
password: raspbian
doesn't seem to work

**Comment by KoopsF** [comment]
ah, thanks.
that did the job!
