### ISSUE TITLE
/root filesystem performance improvements

### ISSUE THREAD

**Issue by pleasantone** [debian-pi/raspbian-ua-netinst#21]
Some research was done here[1] and adapted by the OpenElec raspberry pi folks for significantly increasing the SD card performance by block aligning the ext4 filesystem such that read/write/erases drop on sector boundaries.

While determining the actual block alignments (4k/8k/16k) might be a bit of a pain, we win at all three alignments if we start the root filesystem on a block that is a modulo of 32768 (16k at 512 bytes/block).

Then people can easily fine-tune ext4 sector sizes if you allow us access to the mkfs.ext4 options (e.g. someone with 4k alignment might do: -O ^has_journal -E stride=2,stripe-width=1024 -b 4096)

Thoughts?

[1] http://blogofterje.wordpress.com/2012/01/14/optimizing-fs-on-sd-card/

**Comment by diederikdehaas** [comment]
The options are available and I have no intention of changing the defaults, so it's time to close this issue.
