### ISSUE TITLE
check for required utils

### ISSUE THREAD

**Issue by goranche** [debian-pi/raspbian-ua-netinst#228]
The scripts don't check if required utils (zip for example) are available on the build machine.

Adding a code section (or separate script to be included) to do so should be quite straightforward :smile: 
In case a needed util doesn't exist, a message should be displayed to the user, ideally with instructions on how to install it.

**Comment by diederikdehaas** [comment]
> should be quite straightforward

I'm not so sure about that, when you think of all the different systems this can be used on.
Patches welcome, but it's unlikely I will spend time on this.
What's wrong with `BUILD.md`?

**Comment by goranche** [comment]
> when you think of all the different systems

I'm aware of this... that's why I added the "should be" :wink: 

I actually added this as a placeholder for some code I will be working on (and adding as a PR)...

**Comment by diederikdehaas** [comment]
Ok :+1:

**Comment by goranche** [comment]
huh... curl wasn't found on one of my servers :smile:

**Comment by diederikdehaas** [comment]
Ping?

**Comment by Mausy5043** [comment]
Closing. 
Feel free to re-open if required.
