### ISSUE TITLE
Base preset bricks kernel installation

### ISSUE THREAD

**Issue by Saij** [debian-pi/raspbian-ua-netinst#253]
Hi,

when you choose the base preset to install a Raspberry PI 2 you'll always get a RSOD (Rainbow Screen Of Death) because it'll not install the module ${kernel_meta_package}.
In line 304 of /scripts/etc/init.d/rcS the variable cdebootstrap_cmdline will be completly overwritten.

Using the server preset and everything will be fine.

Greetings
Saij

**Comment by diederikdehaas** [comment]
Thanks for your report :+1: 

Note to self: also check other presets when testing :wink:

**Comment by Saij** [comment]
Little Quick Fix:

in installer-config.txt just put following line
packages=${kernel_meta_package}

**Comment by diederikdehaas** [comment]
The fix is included with v1.0.8 of the installer, so it should now just work.
