### ISSUE TITLE
Will SD-Card installed on B+ work on A+?

### ISSUE THREAD

**Issue by niun** [debian-pi/raspbian-ua-netinst#262]
I am trying to figure out, how to install raspian-ua-netinst on a Raspberry Pi A+. Is there a way to prepare an image with an old Raspberry Pi B? Or will it work with a Raspberry Pi B+?

**Comment by diederikdehaas** [comment]
You should be able to create an image with the net installer on a Pi 1B, 1B+ and then transfer the SD card to an A+. You should also be able to do it with a 2B, but that'll be a bit more involved.

**Comment by niun** [comment]
Thank you very much, I will buy an A+ and try what I can achieve with my Pi B.
