### ISSUE TITLE
Raspi Firmware - RPI-Update - Possible?

### ISSUE THREAD

**Issue by Zuendapp** [debian-pi/raspbian-ua-netinst#267]
Hello,

is there any need to install the github software rpi-update?
Does is work?

Thank you very much!
Best regards
Stefan

**Comment by diederikdehaas** [comment]
> is there any need to install the github software rpi-update?

No. The current advice is to actually **NOT** use it.
(unless specifically asked to do so and/or you want to write code for the firmware and/or kernel)

If you really do want it, it's available in the raspberrypi.org repository.

**Comment by Zuendapp** [comment]
Hi,

ok thank you!
How can I install the newest firmware from raspbberypi.org repository?

Thank you very much!

Stefan

**Comment by diederikdehaas** [comment]
Install the `raspberrypi-bootloader` package. This package contains both the raspberrypi.org kernel and firmware and will uninstall some other packages.
After that comment out or delete the `kernel` and `initramfs` lines from `/boot/config.txt` and reboot

**Comment by jedie** [comment]
> Install the raspberrypi-bootloader package. This package contains both the raspberrypi.org kernel and firmware and will uninstall some other packages.
After that comment out or delete the kernel and initramfs lines from /boot/config.txt and reboot

Please add this to README!
