### ISSUE TITLE
Custom install: static IP

### ISSUE THREAD

**Issue by Marbaf** [debian-pi/raspbian-ua-netinst#269]
Hi,

First sorry because following is a question and not an identified issue. Feel free to remove if inappropriate.

I tried to install master branch with static IP declaration inside installer-config.txt on PI B rev2.
Each time it failed whereas installation works fine with default dhcp settings.
Could the reason be that I let parameter ip_nameservers empty ?

Kind regards

**Comment by goranche** [comment]
> Could the reason be that I let parameter ip_nameservers empty

most probably :wink: 
if you don't specify any name server (DNS server), the installer will not be able to resolve the addresses of the repositories it needs for the packages it needs to install

**Comment by diederikdehaas** [comment]
> Could the reason be that I let parameter ip_nameservers empty ?

That is VERY likely. If you don't use dhcp, you need to specify all things needed to make a network connection manually.

**Comment by Marbaf** [comment]
Thank you guys.
Indeed when I change an already running pi from DHCP to static IP, system already knows about nameservers.
Apologize for inconvenience.
