### ISSUE TITLE
Is enabling root really necessary?

### ISSUE THREAD

**Issue by erosproject** [debian-pi/raspbian-ua-netinst#27]
In rcS, lines 352-354, you enable root login. Most distros recommend against this. Is there a good reason to do this? If I were to remove these lines would the user be "pi" like in the default Raspbian distro? If not, how do we create "pi" in this script so that we don't have to enable root?

# allow root login
echo -n "Configuring installed system... "
echo -n root:$rootpw | chroot /rootfs /usr/sbin/chpasswd || fail

**Comment by Mausy5043** [comment]
Given changes in v1.1.x as a result of #82 I guess we could disable root logins on v1.1.x too?

**Comment by Mausy5043** [comment]
And apparently I spoke too soon. Root logins are optional as of v1.1.x.
https://github.com/debian-pi/raspbian-ua-netinst/blob/v1.1.x/scripts/etc/init.d/rcS#L671-L694
