### ISSUE TITLE
Pi2 stuck at 600mhz

### ISSUE THREAD

**Issue by ric96** [debian-pi/raspbian-ua-netinst#271]
By default the pi2's clockspeed it stuck at 600mhz event if it is under 100% load.
Solution: install cpufrequtils

**Comment by diederikdehaas** [comment]
Confirmed. 
The default scaling governor is _powersave_ and by installing `cpufrequtils` that changes to _ondemand_

**Comment by kpfleming** [comment]
Thanks for reporting this! Giving up 33% of the CPU speed is not desirable :-)

**Comment by 5shekel** [comment]
thanks for this project, installed without a hitch. 
but would love seeing this installed (or mentioned) by default
