### ISSUE TITLE
couldn't download pool/main/ncurses libtinfo 5_5

### ISSUE THREAD

**Issue by Bobbaone** [debian-pi/raspbian-ua-netinst#275]
At trying to install the img at the raspberry, a error appears:

couldn't download pool/main/ncurses/libtinfo5_5.9-10_armhf.deb

wget ERROR 404

**Comment by goranche** [comment]
is this happening every time? say today? :smile: 

I think this might be a transient issue at the packages repository, over which we don't have any control

**Comment by Bobbaone** [comment]
Hm, i dont use it anymore, i use dietpi...

**Comment by goranche** [comment]
ok, in that case I guess I can close this issue...

if you feel it's still needed, you can of course reopen it

**Comment by diederikdehaas** [comment]
> couldn't download pool/main/ncurses/libtinfo5_5.9-10_armhf.deb

JFTR: that path is incorrect, it should've been `pool/main/n/ncurses/libtinfo5_5.9-10_armhf.deb`
