### ISSUE TITLE
Filename problem with 'installer-config.txt'

### ISSUE THREAD

**Issue by mike632t** [debian-pi/raspbian-ua-netinst#278]
Not sure if this is really an issue but a note in the readme would have saved a few hours!  

Basically when creating the 'installer-config.txt' file it is probably best to do so from the command line.  I eventually discovered that creating a new file using  'Caja' and then renaming it by pasting in the new filename from the text on https://github.com/debian-pi/raspbian-ua-netinst (so as to avoid any typos) doesn't have the desired effect.  In the GUI it looks correct but the hyphen gets pasted in as a utf8 character - so the filename doesn't actually match the name that install script is looking for and the custom settings are not applied.  When using 'ls' in a terminal window the problem was obvious!  (Doh)

**Comment by diederikdehaas** [comment]
This sounds like a 'Caja'/browser issue and has no bearing on this project. 
You can easily create the `installer-config.txt` file using a GUI app like Dolphin/Nautilus/Windows Explorer without a problem (command line is fine too). But copy & paste inside a browser window can indeed have the effect that special characters, like `-`, get a special treatment.
