### ISSUE TITLE
Qemu emulation

### ISSUE THREAD

**Issue by mcanevet** [debian-pi/raspbian-ua-netinst#34]
It would be great if we could use qemu to debug the installer but I don't really know how to make it work.

I tried with this command line without any success:

```
qemu-system-arm -kernel kernel_install.img -initrd installer.cpio -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "consoleblank=0"
```

The only thing I get is a black screen.

Any idea ?

**Comment by hadess** [comment]
I'll go back to one of the original comments about "abusing the kernel command-line". It's not only the kernel's. You're more than welcome to add more parameters you might need, just make sure to namespace them. So "raspbian-ua-netinst.boot=/dev/sda" is a fine solution.

**Comment by goranche** [comment]
> It's not only the kernel's

I personally don't agree with that... it *is* the kernels command line (even the name says so :wink: ) and shouldn't be used for other things (unless there really is no other way, and even then you should be able to find another way)

**Comment by hadess** [comment]
Do you want a list of things that aren't the kernel and that use the kernel command-line? Installers, init systems, boot splashes, and usually, hardware detection override (there's a couple of them in GNOME for that purpose).

**Comment by goranche** [comment]
do you think that such a list would change my opinion about the **kernel command line** being a kernel thing? :wink: 
I would call that list and example of how not to do things :angel:

**Comment by diederikdehaas** [comment]
I think it's much better to build for QEMU then add 'run-time detection' for QEMU in rcS.
This is a diff from a local branch I've used to add QEMU support:
``` diff
diff --git a/build.sh b/build.sh
index 661cc03..830a44f 100755
--- a/build.sh
+++ b/build.sh
@@ -2,6 +2,8 @@
 
 set -e
 
+QEMU="true"
+
 KERNEL_VERSION=3.12-1-rpi
 INSTALL_MODULES="kernel/fs/f2fs/f2fs.ko"
 INSTALL_MODULES="$INSTALL_MODULES kernel/fs/btrfs/btrfs.ko"
@@ -213,6 +215,17 @@ cp tmp/lib/*/libz.so.1  rootfs/lib/libz.so.1
 cd rootfs && find . | cpio -H newc -ov > ../installer.cpio
 cd ..
 
+if [ "$QEMU" = "true" ] ; then 
+    # let's also make an installer.cpio suitable for qemu
+    sed -i '/^bootdev=/s|/dev/mmcblk0|/dev/sda|' "rootfs/etc/init.d/rcS"
+    sed -i '/^bootpartition=/s|/dev/mmcblk0p1|/dev/sda1|' "rootfs/etc/init.d/rcS"
+    sed -i '/^rootdev=/s|/dev/mmcblk0|/dev/sda|' "rootfs/etc/init.d/rcS"
+    sed -i '/^rootpartition=/s|$|/dev/sda2|' "rootfs/etc/init.d/rcS"
+    cd rootfs && find . | cpio -H newc -ov > ../installer-qemu.cpio
+    cd ..
+    # end qemu part
+fi
+
 rm -rf tmp
 rm -rf rootfs
 
@@ -235,7 +248,21 @@ if [ -d config ] ; then
     cp -r config/* bootfs/config
 fi
 
-ZIPFILE=raspbian-ua-netinst-`date +%Y%m%d`-git`git rev-parse --short @{0}`.zip
+ZIPFILE_BASE=raspbian-ua-netinst-`date +%Y%m%d`-git`git rev-parse --short @{0}`
+ZIPFILE=${ZIPFILE_BASE}.zip
 rm -f $ZIPFILE
 
 cd bootfs && zip -r -9 ../$ZIPFILE *; cd ..
+
+if [ "$QEMU" = "true" ] ; then 
+    # replace installer.cpio with the qemu variant
+    rm bootfs/installer.cpio
+    cp installer-qemu.cpio bootfs/installer.cpio
+    ZIPFILE_QEMU=${ZIPFILE_BASE}-qemu.zip
+    rm -f $ZIPFILE_QEMU
+    cd bootfs && zip -r -9 ../$ZIPFILE_QEMU *; cd ..
+    # restore the original installer.cpio
+    rm bootfs/installer.cpio
+    cp installer.cpio bootfs/
+fi
+
```
This was before the RPi2 support code was there and it's probably easier to do now.

**Comment by hadess** [comment]
The problem I see with this is that you're modifying the rootfs files, so the changes are not undone when you create a non-QEmu images, and it makes it impossible to create an installer that go through the image creation on QEmu but targetted at physical Raspberry Pis.

**Comment by diederikdehaas** [comment]
The idea is to create either an image for use with QEMU or an image for the RPi.
When you first create an image for QEMU and then you want to create one for the RPi, you'd run `./clean.sh` first.

**Comment by hadess** [comment]
Fair enough.

**Comment by Nekrofage** [comment]
Hi, 

I have these errors: 
[~/QEMU] ➔ ./raspbian-ua-netinst-qemu-prep.sh raspbian-ua-netinst-20150309-gitf31b204.img 
Image resized.
./raspbian-ua-netinst-qemu-prep.sh: ligne 39: ../disk-image/boot/installer.cpio: Aucun fichier ou dossier de ce type
sed: impossible de lire etc/init.d/rcS: Aucun fichier ou dossier de ce type
sed: impossible de lire etc/init.d/rcS: Aucun fichier ou dossier de ce type
sed: impossible de lire etc/init.d/rcS: Aucun fichier ou dossier de ce type
sed: impossible de lire etc/init.d/rcS: Aucun fichier ou dossier de ce type

How to resolve them ?

Thx.

**Comment by Nekrofage** [comment]
I resolved my problem, see my tuto : http://framboisepi.fr/lancement-de-raspbian-a-partir-de-qemu/

**Comment by diederikdehaas** [comment]
Anyone has any tips as to how to get networking working with QEMU?
I can't even get pinging based on IP address working :-(

**Comment by JedMeister** [comment]
Not sure @diederikdehaas. 

I'm using QEMU from Wheezy backports and my guest was built with v1.0.6 of the UA-netinstall. I'm running a 3.10 kernel I compiled myself and it all just works OOTB... 

Although FWIW by default QEMU uses NATed network AFAIK. So outgoing should be fine. I use redirection to allow incoming SSH connections: i.e. I use `-redir tcp:5022::22` then connect to the RPi guest (from the host) via `ssh -p 5022 root@localhost`

**Comment by diederikdehaas** [comment]
Looks like it was false alarm :smile: 
I was working with a development image and in that dns didn't work. My first step in troubleshooting network issues is doing a ping, but [according to the documentation that's expected](http://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29):
_ICMP traffic does not work (so you cannot use ping within a guest)_
But now that I've fixed the dns issue, it is working properly.
This is how I use QEMU (on Debian Sid) atm:
```sh
$ stty intr ^]
$ qemu-system-arm -kernel "kernel-3.12.9-1+rpi2-qemu" -initrd "installer-qemu.cpio" \
 -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio \
-append "consoleblank=0 console=ttyAMA0 console=ttyS0" \
"raspbian-ua-netinst-20150325-git17e4c6d.img"
```
The first command is to remap quitting QEMU to Ctrl-] (instead of Ctrl-C) and then it starts QEMU and I get a serial console to interact with it, which works great.
I'm (also) using a custom compiled kernel and the image I'm using is a freshly build installer which then gets put through @dhanar10's excellent script, which also produces the initrd file.

I finally got around to (trying to) develop using QEMU and I have to say it's quite nice :smile:

**Comment by diederikdehaas** [comment]
Since we're doing runtime detection now to distinguish between RPi 1 and 2, doing so for QEMU might not be such a bad idea. The following commands look useful in **my** situation:
```sh
grep Hardware /proc/cpuinfo | cut -d " " -f 2-3
if [ $(dmesg | grep QEMU | wc -l) -gt 0 ] ; then
   QEMU=true
fi
```

**Comment by bbinet** [comment]
+1 it would be great to be able to run the same image on both rpi and Qemu

**Comment by goranche** [comment]
I'm removing this from the v1.1.0 milestone, as there doesn't seem to be too much interest in working on this one... not closing it though, as it is still an interesting one

**Comment by Mausy5043** [comment]
Closing this issue as there hasn't been any activity here for more than a year. If you feel the closure was in error please feel free to re-open with your comment and/or new info.

**Comment by Mausy5043** [comment]
ref: https://stackoverflow.com/questions/38837606/emulate-raspberry-pi-raspbian-with-qemu
