### ISSUE TITLE
invalid user when swap make

### ISSUE THREAD

**Issue by cleloup** [debian-pi/raspbian-ua-netinst#343]
Hi

<< Optional: Create a swap file with dd if=/dev/zero of=/swap bs=1M count=512 && mkswap /swap && chown og-r /swap >>

chown: invalid user: 'og-r'.

can you help me ?

**Comment by diederikdehaas** [comment]
That's a fault in the documentation, it should be `chmod 600 /swap`.
It is fixed in the v1.0.x branch and I'll probably make a small release soon so it is also part of `master` (which you normally see).

**Comment by diederikdehaas** [comment]
With the release of v1.0.8.1 this is now fixed.
