### ISSUE TITLE
Headless ssh only config for installer?

### ISSUE THREAD

**Issue by DdraigX** [debian-pi/raspbian-ua-netinst#351]
Howdy,

So I just discovered this and I'm testing it out. Is there a way to set the install to headless only in the installer-config.txt?

Thanks,
Ddraig

**Comment by diederikdehaas** [comment]
I'm probably not getting what you mean, because by default it will install a headless system, as in no Xorg or anything like that.

**Comment by DdraigX** [comment]
Thanks that's exactly what I was wondering!
