### ISSUE TITLE
W: Can't find package omxplayer for inclusion

### ISSUE THREAD

**Issue by aristosv** [debian-pi/raspbian-ua-netinst#353]
This is my installer-config.txt
```
hostname=ClientX
rootpw=passhere
cdebootstrap_cmdline='--flavour=minimal --include=linux-image-rpi2-rpfv,kmod,ifupdown,net-tools,isc-dhcp-client,ntp,openssh-server,iputils-ping,wget,ca-certificates,rsyslog,dialog,locales,less,ntpdate,nano,lftp,mpg123,omxplayer,sshpass,bc,psmisc,alsa-utils,curl,mailutils
bootsize=+64M
```
During installation I get a message
```W: Can't find package omxplayer for inclusion```
After the installation is finished I can install it by running "apt-get install -y omxplayer" but not during the automated installation. What could I be doing wrong here?

**Comment by diederikdehaas** [comment]
`omxplayer` is in the raspberrypi.org repo and you can only install packages from the raspbian.org repo during the initial installation phase. If you do the following in `post-install.txt` it should work:
```
chroot /rootfs /usr/bin/apt-get -y install omxplayer
```

**Comment by aristosv** [comment]
thank you
