### ISSUE TITLE
Setting max_usb_current

### ISSUE THREAD

**Issue by sorinpohontu** [debian-pi/raspbian-ua-netinst#362]
I need to install with an external USB HDD and I need to set max_usb_current=1 at initial boot. How can I do that ?

I didn't find any reference about this.

**Comment by goranche** [comment]
after writing the installer to your SD card, you can open config.txt on the SD card and add this option.

I'd recommend against this, though, if you're not absolutely sure you have a good quality power supply that's capable of delivering reliable and clean power at 2A+

**Comment by sorinpohontu** [comment]
I know what I'm doing, just needed the info :)
Thanks.

**Comment by goranche** [comment]
> just needed the info

:+1:  great :wink:
