### ISSUE TITLE
stuck at "retrieving release"

### ISSUE THREAD

**Issue by fredericofs** [debian-pi/raspbian-ua-netinst#376]
It could be something with my connection. But my install is stuck at "retrieving release".
After some minutes I got some 'wget' unable to get release errors, and the msg:
10 seconds to hit enter to go to shell
and it reboots.
I added goranche's read-only post install script.txt.

**Comment by diederikdehaas** [comment]
IPv6?

**Comment by fredericofs** [comment]
yep, it seems my home connection turned ipv6 last week

**Comment by fredericofs** [comment]
I just switched my home connection to ipv4 and it is working now.

**Comment by diederikdehaas** [comment]
Work is underway to also support IPv6, but we're not there yet. 
If you are able and willing with testing it, that would be great :+1:
