### ISSUE TITLE
installer-config.txt docs

### ISSUE THREAD

**Issue by blondie63** [debian-pi/raspbian-ua-netinst#392]
Are there some documentation about settings syntax on this file?

**Comment by Mausy5043** [comment]
The README.md should clarify all.

**Comment by blondie63** [comment]
packages name are debian default packages name ?
preset=server or.. ?

**Comment by Mausy5043** [comment]
From the README.md:
> packages= # comma separated list of extra packages


Yes, as you guessed. These are the package names that you would use in the `apt-get install` command.

...

> Available presets: server, minimal and base.

**Comment by Mausy5043** [comment]
Assuming your question is answered I'm closing this issue. If you have a follow-up question (after reading the documentation ;-) ) feel free to re-open or open a new issue.
