### ISSUE TITLE
Additional `final_action`

### ISSUE THREAD

**Issue by Mausy5043** [debian-pi/raspbian-ua-netinst#402]
Currently, 3 possible `final_action`s are provided: `halt`, `poweroff` and `reboot` (by `*`).

Proposal is to add one more: `shell` which starts a shell at the end of the installation. This can be useful for inspecting the installed system at the end of the install. However, the `umount`s should then come after the shell-drop.  ... or the shell should be started before the `umount`s ;-)

**Comment by goranche** [comment]
💭 I'm not sure I like this one... a shell isn't a "final action", I really doubt it has real value for installation purposes, for development purposes you can achieve this in post-install.txt

**Comment by Mausy5043** [comment]
you're right. forgot about `post-install.txt` 👍
