### ISSUE TITLE
GUID Partition Table

### ISSUE THREAD

**Issue by ShorTie8** [debian-pi/raspbian-ua-netinst#406]
Not really a issue, but more of a question.
Has anyone tried to use parted's GPT partition table instead of fdisk's mbr ??
Heard it might work on rpi2/3, but unconfirmed.

**Comment by diederikdehaas** [comment]
I have no reason to believe it won't work, but I haven't tried it.

**Comment by goranche** [comment]
the firmware is supposed to support booting from a GPT partitioned SD card, but I'm not sure about the kernel (and actually doubt it does support it)... a custom kernel (with support for GPT partitions) should have no problem, though...

**Comment by ShorTie8** [comment]
hmmm, don't see no specific gpt stuff, but do see a CONFIG_BLOCK_COMPAT
