### ISSUE TITLE
outdated documentation in README.md

### ISSUE THREAD

**Issue by oupala** [debian-pi/raspbian-ua-netinst#407]
In README.md, section [Reinstalling or replacing an existing system](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/README.md#reinstalling-or-replacing-an-existing-system), the documentation is outdated:

> Make sure you still have kernel_install.img and installer.cpio.gz in your /boot partition.

I have some rpi1 and rpi2 versionned files:

```bash
/boot>ls kernel*
kernel.img  kernel-rpi1_install.img  kernel-rpi2_install.img
/boot>ls installer*
installer-rpi1.cpio.gz  installer-rpi2.cpio.gz
```

Documentation should be updated.

**Comment by Mausy5043** [comment]
Oops.

**Comment by Mausy5043** [comment]
Thank you for bringing this to our attention.
We'll look into it.
If you wish you are welcome to contribute. The guidelines for contributing are [here](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/CONTRIBUTING.md).

**Comment by oupala** [comment]
Well, by reporting this issue, I **am** contributing.

I would have created a pull request if only I would know how to update the documentation.

Next time I have anything to report, and to fix by myself, I'll create a pull request.

**Comment by Mausy5043** [comment]
👍

**Comment by thijstriemstra** [comment]
@oupala try https://github.com/debian-pi/raspbian-ua-netinst/edit/master/README.md, edit and save.

**Comment by oupala** [comment]
I was not clear in my previous message. In fact, I know how to edit a file with github. My problem is that I don't know what to change in the README file.

**Comment by Mausy5043** [comment]
Had some time to spare so I threw something together.

**Comment by diederikdehaas** [comment]
The change has now been merged, thus closing the issue. Thanks for the report :-)
