### ISSUE TITLE
Enable rng-tools by default

### ISSUE THREAD

**Issue by Asmod4n** [debian-pi/raspbian-ua-netinst#42]
Since this is a headless install, entropy for ssh-host-keys will be very low, starting rngd before key creation should resolve that.

I just don't know if the default kernel has support for the raspi hardware rng.
I am rolling a self compiled kernel with hard-float support. (the kernel sources from https://github.com/raspberrypi/linux compile every arm kernel with soft-float)

**Comment by Asmod4n** [comment]
This could be easily resolved by the kernel.. if it would block /dev/urandom on boot until it has enough entropy :/

**Comment by kpfleming** [comment]
That's not how /dev/urandom works. Blocking there would break applications. If an application needs guaranteed amounts of entropy, it must use /dev/random.

**Comment by Asmod4n** [comment]
Only Linux is showing this behavior, every other OS waits at boot for their non blocking random device to have enough entropy :/

**Comment by kpfleming** [comment]
Even if that's true, this isn't the place to discuss it, since the team here has no responsibility for the Linux kernel :-)

**Comment by diederikdehaas** [comment]
A VERY interesting thread on the raspberrypi.org forums: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=126892

**Comment by Mausy5043** [comment]
How does one find out if the SSH keys were generated using the bcm2708-rng module or not?

**Comment by diederikdehaas** [comment]
You can't (run a SSH key through a program to figure out which (if any) HWRNG was used).

For systems installed with this installer, none were generated with the assistance of bcm2708-rng unless the user explicitly (in `post-install.txt` for example) removed the generated keys, modprobe-d the module, installed rng-tools and started the service and _then_ ran `dpkg-reconfigure openssh-server`.

**Comment by Mausy5043** [comment]
I've been doing some experiments and it seems that on the installed system `modprobe bcm2708-rng` is enough to enable the hardware RNG.

I need some kind of test to determine if the RNG in use actually **is** the hardware one or whether it really is just the software RNG that's active.

Also, is it necessary to install the `rng-tools` package? Or would it be enough to enable the kernel module?

**Comment by Mausy5043** [comment]
Below some references I used to understand this subject. I'm parking them here for all to reference.

https://blog.cloudflare.com/ensuring-randomness-with-linuxs-random-number-generator/
https://www.howtoforge.com/helping-the-random-number-generator-to-gain-enough-entropy-with-rng-tools-debian-lenny
https://security.stackexchange.com/questions/47475/testing-a-hardware-random-number-generator
http://scruss.com/blog/2013/06/07/well-that-was-unexpected-the-raspberry-pis-hardware-random-number-generator/

**Comment by diederikdehaas** [comment]
Thanks for the links @Mausy5043 :+1: 
> Also, is it necessary to install the rng-tools package? Or would it be enough to enable the kernel module?

I think the `rng-tools` package is necessary as it feeds the random numbers/data from the HWRNG into the kernel pool. And in turn the **kernel** is responsible for providing random numbers.

**Comment by Mausy5043** [comment]
Here's one I prepared earlier:
RFC: https://github.com/Mausy5043/raspbian-ua-netinst/pull/1

This a PR in progress. It looks like its working. Needs some more testing, but I'm confident this will be it.
The `rng-tools` package is added to installations of the `minimal` or `server` type. The `base` installation doesn't get the HWRNG and `rng-tools` installed to cater the hardcore minimalists among us. :stuck_out_tongue_winking_eye: 

Shoot!

**Comment by Mausy5043** [comment]
[This article](https://en.wikipedia.org/wiki//dev/random) explains that 

> [t]he Linux kernel supports several hardware random number generators. The raw output of such a device may be obtained from /dev/hwrng.
> With Linux kernel 3.16 and newer, the kernel itself mixes data from hardware random number generators into /dev/random on a sliding scale based on the definable entropy estimation quality of the HWRNG. This means that no userspace daemon, such as rngd from rng-tools is needed to do that job.

@goranche helped me analyse the Linux kernel source. 
The kernel reads the hardware device [using `add_hwgenerator_randomness()`](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/char/random.c#n1844)
which gets called by the kernel [in `hwrng_fillfn()`](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/char/hw_random/core.c#n426)

This means that we only need to load the appropriate kernel module (`bcm2708-rng`) to make `/dev/hwrng' available to the kernel.

That makes life a lot easier. It means we can simply activate the device by `modprobe`ing the kernel module `bcm2708-rng`. The kernel does the rest. See PR #359.

**Comment by Asmod4n** [comment]
@Mausy5043 yay \o/

**Comment by diederikdehaas** [comment]
I regard the Arch wiki **VERY** high and they say you (really) should use `rng-tools`:
https://wiki.archlinux.org/index.php/Rng-tools

**Comment by Mausy5043** [comment]
Reading [this](https://bugs.launchpad.net/raspbian/+bug/1275337) I tend to agree that rng-tools would be needed.

**Comment by diederikdehaas** [comment]
With the merge of #360 this issue is resolved :smile:
