### ISSUE TITLE
Status of the v1.1.x branch compared to v1.0.x

### ISSUE THREAD

**Issue by bbinet** [debian-pi/raspbian-ua-netinst#422]
I was wondering what is the status of the v1.1.x branch compared to v1.0.x?
What are the new features, enhancements of the v1.1.x branch?

Also, do you know when a new release will be published?

**Comment by kpfleming** [comment]
I know one item: IPv6 support, which is on my agenda to complete this weekend.

**Comment by BenjaminHae** [comment]
Support for the Pi Zero

**Comment by bbinet** [comment]
Ok, so is it safe to start a new project based on the v1.1.x installer?

**Comment by diederikdehaas** [comment]
> is it safe to start a new project based on the v1.1.x installer?

Yes. Keep in mind that new features can still be added to v1.1.x though.

**Comment by bbinet** [comment]
Ok, thanks.

**Comment by diederikdehaas** [comment]
For the most part v1.1.x is right now as it will be released though of which a first alpha should get out this month.
