### ISSUE TITLE
Add files to be put onto the installation?

### ISSUE THREAD

**Issue by Jodes81** [debian-pi/raspbian-ua-netinst#430]
I want to add files to the installer which would be copied onto the final installation. They might include:

Configuration files that replace those in the default installation once installation is complete. (Which I would trigger using _post‑install.txt_.) E.g. /root/.bashrc, samba config files, etc.

Other files might be PHP scripts, Node.JS files, images, css files, compiled C binaries or what have you. 

Is this already possible? If not, how could it be done?

**Comment by Jodes81** [comment]
All files loaded onto the SD card prior to installation are copied into /boot/

**Comment by Mausy5043** [comment]
As of v1.1.x you can put your files in `config/files`. Look for "Bring your own files" in the `README.me` of v1.1.x.

**Comment by Mausy5043** [comment]
@Jodes81 ^^
