### ISSUE TITLE
ln: failed to create hard link

### ISSUE THREAD

**Issue by Mausy5043** [debian-pi/raspbian-ua-netinst#440]
I get this error during the installation and sofar I've always ignored it.
```
Processing triggers for initramfs-tools (0.120+deb8u2) ...
ln: failed to create hard link ‘/boot/initrd.img-4.4.0-1-rpi.dpkg-bak’ => ‘/boot/initrd.img-4.4.0-1-rpi’: Operation not permitted
update-initramfs: Generating /boot/initrd.img-4.4.0-1-rpi
```

However, when using `apt-get` I frequently also see this error. It's starting to annoy me. What causes this? And what can/must be done to get rid of it?

**Comment by goranche** [comment]
`/boot` is a FAT filesystem, which doesn't support hard links

**Comment by Mausy5043** [comment]
ofcourse.
😞

**Comment by diederikdehaas** [comment]
> the /boot partition has to be a FAT filesystem

AFAIK the first partition must be FAT and must contain the firmware/bootloader files.
http://sjoerd.luon.net/posts/2015/02/debian-jessie-on-rpi2/ had it mounted on `/boot/firmware` I believe which makes me think that *technically* you can have `/boot/` as ext4 (for example) and have `/boot/firmware` be the first partition with FAT. The *practical* problem is that (currently) the package that provides the firmware/bootloader files places them in `/boot/` and switching that in Raspbian will cause (a lot of) problems.

But ... there is https://wiki.debian.org/RaspberryPi3 and the firmware (for RPi3) will get placed in `/boot/firmware`, see the [postinstall of that package](https://anonscm.debian.org/cgit/pkg-raspi/raspi3-firmware.git/tree/debian/raspi3-firmware.postinst)

**Comment by goranche** [comment]
in that case I think you'd have to put the booting kernel on that partition as well, so you wouldn't accomplish anything, really...
