### ISSUE TITLE
Newbie Questions

### ISSUE THREAD

**Issue by ChocoFruit** [debian-pi/raspbian-ua-netinst#442]
Hello developer :)

I am interested in using your system on my new raspberry pi 3. But I have some questions and I hope here is the right place to ask.

1) Can I use the installtion guide also for raspberry pi 3?
2) What do I need to do to install wifi? (for client use and to creat an AP)
3) How do I make updates (e.g. kernal updates or new linux versions for my pi)?

I am new to linux, but really want to get into it ^-^
Also many manuals are for regular debian, I dont want to mess up my new pi.

Thanks a lot!!!

And have nice christmas days and a happy new year!

**Comment by BenjaminHae** [comment]
> I am new to linux, but really want to get into it ^-^
> Also many manuals are for regular debian, I dont want to mess up my new pi.
Cool! Learning Linux is always a good idea. You don't need to be afraid. You can at most break your sd card your pi should stay ok(as long as you don't overclock it or do something with the pins).

1. If you use the master branch installing on a raspberry pi 3 should work.
3. For getting updates you use `sudo apt-get update && sudo apt-get upgrade`. But kernel updates etc. aren't that common in this installation as it follows the debian philosophy. You'll mostly get security updates for the current versions.
