### ISSUE TITLE
GPIO unprivileged access

### ISSUE THREAD

**Issue by ThomDietrich** [debian-pi/raspbian-ua-netinst#448]
We need to access the gpio pins from inside an application without root privileges. As you probably know, a Raspbian update brought a kernel functionality and a "gpio" group to access these IOs as user of this group. See: http://www.savagehomeautomation.com/projects/pi4j-now-supports-non-privileged-access-no-more-rootsudo.html

raspbian-ua-netinst (v1.1.x) doesn't provide this feature. Any plans to implement it? Do you know what's needed?

**Comment by Mausy5043** [comment]
There are no plans to provide this feature.
