### ISSUE TITLE
booting from USB, without microSD

### ISSUE THREAD

**Issue by aristosv** [debian-pi/raspbian-ua-netinst#449]
I realize I can have the system installed on a USB drive using the `usbroot=1` option. But with the new [bootmodes](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md) for the Raspberry Pi 3, the OS can be booted without a microSD card at all.

Will this be a possibility for raspbian-ua-netinst?

**Comment by Mausy5043** [comment]
This experimental feature is not possible with the raspbian-ua-netinst repo.
