### ISSUE TITLE
Dynamic /dev/loop support

### ISSUE THREAD

**Issue by richard-scott** [debian-pi/raspbian-ua-netinst#450]
Hi,

I have an Ubuntu system that has the live kernel patching activated. This process consumes 3 loop devices and stops the 'buildroot.sh' script from working as this depends on /dev/loop0 which is currently in use.

This [PR](https://github.com/debian-pi/raspbian-ua-netinst/pull/431) will detect the next free loop device and use that instead of being fixed to /dev/loop0.

Thanks,

Rich

**Comment by goranche** [comment]
hey, @richard-scott 
thanks for your contribution... and yes, it's true the loop0 is fixed, and "probably" should be changed dynamically 😇 

we'll try it out and merge if all works out 👍

**Comment by diederikdehaas** [comment]
With the merge of #431 this issue can be closed
