### ISSUE TITLE
add bash-completion

### ISSUE THREAD

**Issue by CWempe** [debian-pi/raspbian-ua-netinst#458]
I realized that some commands had no auto-completion.

For example, when I type `systemctl re<tab> <tab>` I get nothing.

I installed the `bash-completion` package.

Now I get.

```
$ systemctl re
reboot                 reload-or-restart      reset-failed
reenable               reload-or-try-restart  restart
reload                 rescue
```

I would recommend to integrate `bash-completion` as a default package.

**Comment by Mausy5043** [comment]
Thanks for the idea.

However, we want to offer users an installer that is small and has basic functionality. Any additional desired functionality can be added by setting the `packages` parameter in the `installer-config.txt` file. 
E.g.:
```
packages="bash-completion,rsync,lsb-release,nfs-common,f2fs-tools,git,nano,tree,curl,zip,bc,htop,lsof,psmisc,screen"
```
