### ISSUE TITLE
1.1.x for rpi

### ISSUE THREAD

**Issue by TimVNL** [debian-pi/raspbian-ua-netinst#463]
Hi,

When will there be a 1.1.x release for the rpi3?

**Comment by bobreese** [comment]
I am also very interested in this....
The current 1.0.9 download has issues on the Pi3
Not seeing wifi
Does not bring up gui on Pi3

**Comment by Bebop182** [comment]
Hello, there's a fork compatible with Pi3 https://github.com/FooDeas/raspberrypi-ua-netinst
