### ISSUE TITLE
switch to regular kernel?

### ISSUE THREAD

**Issue by dimovnike** [debian-pi/raspbian-ua-netinst#465]
is it possible, after it's installed, to switch to a regular kernel so that rpi-update would work?

**Comment by Mausy5043** [comment]
Asked and answered before. 
* See here regarding use of `rpi-update`: https://github.com/debian-pi/raspbian-ua-netinst/issues/225#issuecomment-100497541
* See here regarding change-over to Raspberry Pi Foundation kernel: https://github.com/debian-pi/raspbian-ua-netinst/issues/435#issuecomment-256940661
* **Beware though**: https://github.com/debian-pi/raspbian-ua-netinst/issues/452

**Comment by dimovnike** [comment]
thank you.
