### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by Rombersoft** [debian-pi/raspbian-ua-netinst#477]
Hi Guys! I use mono for developing applications. Please say me I want to know does really raspbian support .NET Core?
About .NET Core here https://www.microsoft.com/net/core#linuxubuntu

**Comment by kpfleming** [comment]
This is not a Raspbian support forum; it's for this installer which is used to install Raspbian. For general Raspbian questions, you'll need to ask on the RPi forums:

https://www.raspberrypi.org/forums/viewforum.php?f=66
