### ISSUE TITLE
dpkg issues

### ISSUE THREAD

**Issue by CustomIRCd** [debian-pi/raspbian-ua-netinst#484]
Whilst watching the installation via a TV (yes i'm that sad) i noticed loads of errors with dpkg pre-dependency problem

Running on RPi3 with latest release (1.1.x) from github. I built the image on a server running ubuntu (latest)

Here's the log
https://gist.github.com/CustomIRCd/8305dcbfcc2442ad88425f217e86ee4c

is this something i could solve with a simple command? it installs fine and system boots just wanted to know what if any effects this error has really or if it can be fixed

**Comment by BenjaminHae** [comment]
Excerpt from Readme:
Note: During the installation you'll see various warning messages, like "Warning: cannot read table of mounted file systems" and "dpkg: warning: ignoring pre-dependency problem!". Those are expected and harmless.

**Comment by CustomIRCd** [comment]
Thanks @BenjaminHae  - i'm not normally that sad to sit and watch it. I'll close this issue then
