### ISSUE TITLE
Release files 1.1.1-beta1 and beta2 are broken

### ISSUE THREAD

**Issue by Zeerix** [debian-pi/raspbian-ua-netinst#485]
I opened this new issue for traceability and clarity of this problem ([see also here](https://github.com/debian-pi/raspbian-ua-netinst/issues/476#issuecomment-318199746)).

The release files of `1.1.1-beta1` and `1.1.1-beta2` contain broken installer-cpio files, so the installer does not boot. This leads to issue #476.

**Comment by Zeerix** [comment]
I just tested `1.1.1-beta3` on a Raspberry Pi 3. The installation was a success.
The installed kernel:
`root@pi3:~# uname -a`
`Linux pi3 4.9.0-2-rpi2 #1 SMP Raspbian 4.9.13-1+rpi3 (2017-05-18) armv7l GNU/Linux`

**Comment by Mausy5043** [comment]
Fixed by beta3
