### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by sathucandy** [debian-pi/raspbian-ua-netinst#505]
whenever i change my mac address in linux during reboot time my net stops working but if i use my original mac address it works just fine so please help me to find a solution for my problem

**Comment by Mausy5043** [comment]
Please review our [contributing guidelines](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/CONTRIBUTING.md).

**Comment by goranche** [comment]
closing for now due to inactivity
