### ISSUE TITLE
USB not working after raspberrypi-bootloader-nokernel upgrade

### ISSUE THREAD

**Issue by Rocco83** [debian-pi/raspbian-ua-netinst#509]
Hi,

I'm on a Raspberry Pi 2 B.
Briefly tested on Raspberry Pi 3 B but i think  
Installed from scratch with Jessie (raspbian-ua-netinst-v1.0.9.img).
Upgraded immediately afterward to Stretch.

After the upgrade and the consequent reboot, the OS start without issue, but the USB ports are not working (e.g.: network led does not power up, keyboard is not recognized)
Restoring the `/boot/bcm27*` files from another raspberry, the USB has started working again after boot.

Seems that the problem came just after the upgrade of
`raspberrypi-bootloader-nokernel_1.20170427-1~nokernel1_armhf.deb`
to
`raspberrypi-bootloader-nokernel_1.20180328-1~nokernel1_armhf.deb`

I have tried out also to run rpi-update in place of the firmware package.
The same USB ports issue is happening.

Not sure if this is netinst related or not, but i have not found bugs on raspbian itself, and the package 10 days or more.

**Comment by diederikdehaas** [comment]
branch v1.1.x is where all the work has been done and I plan to make a new release soon.
This issue sounds like possibly too old firmware/kernel, but I haven't heard of this before.
I'm closing the issue, but feel free to reopen it if it still occurs with a self-build installer from v1.1.x or with one that will be released _soon_ :tm:
