### ISSUE TITLE
switching to 'stretch' release of raspbian

### ISSUE THREAD

**Issue by artynet** [debian-pi/raspbian-ua-netinst#512]
Hello Folks,

I was wondering if I could switch to the latest release of Raspbian just changing the release entries in the 👍 

```
scripts/etc/init.d/rcS
```

file. Is that simple as I think ? thanks in advance.

Kind Regards

**Comment by edlins** [comment]
+1
Using `raspberrypi-ua-netinst` to get `stretch` but their reinstall process is broken.  :disappointed:

**Comment by tomaluca95** [comment]
I'm tring to install strech but it fails

**Comment by diederikdehaas** [comment]
No, that won't work as that version of cdebootstrap-static doesn't know about 'stretch'.
I'm working on a 'buster' update and with that you can install stretch and when the package gets rebuild (by Debian/Raspbian) to pick up a bug fix, you can install buster with it too.

**Comment by diederikdehaas** [comment]
Buster update has been merged into the v1.1.x branch
