### ISSUE TITLE
a start job is running for raise network interfaces

### ISSUE THREAD

**Issue by TFTomSun** [debian-pi/raspbian-ua-netinst#522]
I get this message on a raspberry PI 2 and it takes 5 minutes to finish on every startup.

my installer-config.txt looks like this:
```
username=pi
userpw=xxxx
user_is_admin=1
enable_watchdog=1
packages=curl

```

Edit:
I tried with an empty installer-config, too. Same problem. The installation runs fine, but after the reboot, I get this weird error. Is there a possibility to install an older raspbian version, that has been tested on Raspberry PI 2 with this tool?

**Comment by diederikdehaas** [comment]
Does the problem still occur?

A release is normally tested on all supported versions, so including RPi2. An older version won't do you any good.
It also doesn't sound like a problem with the installer, but with the installed system, so I'm closing this issue for now.
If I can, I'll try to help, but you need to provide more info, f.e. the installation log file. If it does seem to be an installer problem, you/me can reopen this issue again.
