### ISSUE TITLE
Failed to install base: "network/interfaces: no such file or directory" 

### ISSUE THREAD

**Issue by lukehutch** [debian-pi/raspbian-ua-netinst#525]
See screenshot. The only thing I changed in the settings before booting was to set the distribution to "base".

![IMG_20200809_212306](https://user-images.githubusercontent.com/811305/89749858-c7c0de00-da86-11ea-878c-674032c9fc95.jpg)

**Comment by diederikdehaas** [comment]
That's clearly a bug, thanks for reporting it :+1: 
It may take a while before I can fix it, but I will.

**Comment by diederikdehaas** [comment]
It indeed took quite a while, but I just released a new version where this should be fixed. If not, let me know and reopen this issue.
