### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by unclehowell** [debian-pi/raspbian-ua-netinst#528]
Ansible just came to my attention and I'm wondering what are the upsides and downsides versus this approach ?

**Comment by diederikdehaas** [comment]
AFAIK Ansible doesn't/can't install a new OS, which is what this project primarily does.
This project can also install additional packages and that is something Ansible can do too. Which tool you use for that is what the user prefers to do.

**Comment by unclehowell** [comment]
Great solution in anycase.
