### ISSUE TITLE
Hard-coded kernel version - intended ?

### ISSUE THREAD

**Issue by emthornber** [debian-pi/raspbian-ua-netinst#59]
In rcS script at line 475 the version of kernel is hard-coded.  Is this intended given the work done to define and use ${KERNEL_VERSION} ?

**Comment by Mausy5043** [comment]
Are there any plans to change the kernel version to something more recent? I notice that [raspberrypi/linux](https://github.com/raspberrypi/linux) is already at 3.18 but the debian/pi/v1.1.x is still on the old and trusty 3.12 :wink: .

If no plans, What would I need to look out for if I wanted to move up to 3.14 or 3.16 (which are the versions that seem to be mainstream at the moment)? Can I just change the variable KERNEL_VERSION? 

Has it been tried already, and if so, with what results?

**Comment by diederikdehaas** [comment]
The RPF kernel repo has a 3.18 **branch** but they still default to using 3.12 :wink: 

If you want to change the kernel version of the installer, you indeed need to change the KERNEL_VERSION variable. 
If you want to change the kernel version on the installed system, you would need to install a different kernel package. Currently the `linux-image-rpi-rpfv` package gets installed, which in turn installs the linux-image-3.12-1-rpi package.
But there is also a `linux-image-3.16.0-4-rpi` package so if you add that to `packages` it would get installed and with the [kernel upgrade script in place](https://github.com/debian-pi/raspbian-ua-netinst/blob/master/scripts/etc/init.d/rcS#L601) it should also modify `/boot/config.txt` to point to the 3.16 kernel and initramfs.
See also https://github.com/debian-pi/raspbian-ua-netinst/issues/166

**Comment by Mausy5043** [comment]
Thanks :+1: I'll give it a try.
