### ISSUE TITLE
missing /opt/vc/include/bcm_host.h used for compiling

### ISSUE THREAD

**Issue by pipersw** [debian-pi/raspbian-ua-netinst#78]
I compile Domoticz (http://www.domoticz.com) and WiringPi (http://www.wiringpi.com).
During compilation of Domoticz, the makefile (http://sourceforge.net/p/domoticz/code/HEAD/tree/domoticz/CMakeLists.txt) don't find /opt/vc/include/bcm_host.h, and so it show the error message "Not building on Raspberry Pi. GPIO support disabled.".
It not detect the RaspberryPi hardware.

The related lines in CMakeLists.txt:
 try to detect Raspberry Pi hardware and WiringPi library. If found, include GPIO support
find_path(RaspberryPi NAMES bcm_host.h PATHS "/opt/vc/include")
IF(RaspberryPi)
message(STATUS "Building on Raspberry Pi... (bcm_host.h found in ${RaspberryPi})")
find_path(WiringPi wiringPi.h)
IF(WiringPi)
message(STATUS "WiringPi include was found in ${WiringPi}...")
find_library(WIRINGPI_LIBRARY wiringPi)
IF(WIRINGPI_LIBRARY)
message(STATUS "WiringPi library was found in ${WIRINGPI_LIBRARY}...")
add_definitions(-DWITH_GPIO)
target_link_libraries(domoticz ${WIRINGPI_LIBRARY}) 
else()
message(STATUS "==== WiringPi library not found. GPIO support disabled.")
message(STATUS "==== (Please follow http://wiringpi.com/download-and-install/ if you want to use GPIO.)")
ENDIF()
else()
message(STATUS "==== WiringPi include file (wiringPi.h) not found. GPIO support disabled.")
message(STATUS "==== (Please follow http://wiringpi.com/download-and-install/ if you want to use GPIO.)")
ENDIF(WiringPi)
else()
message(STATUS "Not building on Raspberry Pi. GPIO support disabled.")
ENDIF(RaspberryPi) 

So, could you include /opt/vc/include/bcm_host.h ?

If you would inspect the content of bcm_host.h, it is here : https://github.com/raspberrypi/firmware/blob/master/opt/vc/include/bcm_host.h

**Comment by aerickson** [comment]
I'm seeing this now on a raspbian-ua-netinst box I just installed less than a month ago. 

```
root@pi:/etc/apt# apt-cache policy libraspberrypi-dev
N: Unable to locate package libraspberrypi-dev
```

**Comment by diederikdehaas** [comment]
What does your `/etc/apt/sources.list` look like? (And any file in `/etc/apt/sources.list.d/`)

**Comment by aerickson** [comment]
Yes, my /etc/apt/sources.list was bad. I was troubleshooting something earlier and I commented out the default lines and replaced them with the lines on the raspbian site at: https://www.raspbian.org/RaspbianRepository

```
deb http://archive.raspbian.org/raspbian wheezy main contrib non-free
deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free
```

I misread the two default lines and thought that they were talking to the same server (vs one talking to raspbian.org and one talking to raspberrypi.org). The repo setup for raspbian is a little confusing coming from vanilla Ubuntu (that raspberrypi.org provides firmware, etc). 

Sorry for the alarm.

Thanks,
Andy
