### ISSUE TITLE
No DNS lookup in built image

### ISSUE THREAD

**Issue by goranche** [debian-pi/raspbian-ua-netinst#80]
**Note**: this issue has been "resolved" by a workaround, which will stay in place until a permanent solution is ready and tested. busybox-static (the cause of these problems) will be replaced with busybox, and all our troubles will seem so far away :+1: 
:wink: 

=========================================

first off, thanks for this project, love it...
so much so, that I started coding some additional features (starting with locale and timezone from #35), but I'm experiencing some really strange issues when building the install image myself...

first, when running ./build.sh, I'm getting depmod warnings:
depmod: WARNING: could not open /home/goranb/raspbian-ua-netinst/rootfs/lib/modules/3.10-3-rpi/modules.order: No such file or directory
depmod: WARNING: could not open /home/goranb/raspbian-ua-netinst/rootfs/lib/modules/3.10-3-rpi/modules.builtin: No such file or directory

second, when booting from the resulting image, the system doesn't seem to be able to do DNS lookupups.
it get's an IP address, ping works fine, there is a nameserver entry in /etc/resolv.conf (the right one for my network), so ping 74.125.232.16 works, but ping www.google.com doesn't

this doesn't happen when booting the release image, but when I replace installer.cpio (to test my code), the problem starts...

to rule out any problem with my code, I've tried generating an image from the code in the repository (so without my changes), same thing...

any ideas?

the system I'm building on is a 64 bit ubuntu, but I've tried it on raspbian (default from raspberrypi.org) as well...

**Comment by diederikdehaas** [comment]
The current version of raspbian jessie busybox-static does not have this problem, thus closing.
