### ISSUE TITLE
Splitting some config options in config files (like ssh keys)

### ISSUE THREAD

**Issue by diederikdehaas** [debian-pi/raspbian-ua-netinst#94]
> although I kind of like the idea of separating the keys, it will introduce a lot of problems, which will be hard to account for...

Let's discuss possible issues here ... :thought_balloon:

**Comment by Mausy5043** [comment]
mmm. #394 resolves this for you?

**Comment by goranche** [comment]
I guess so... 💭

**Comment by Mausy5043** [comment]
IMHO #394 resolves this issue. Therefore, closing. If you think this issue was closed in error please re-open and add your motivation.
